using SkyBot.Models;

namespace SkyBot.Localization;

/// <summary>
/// Resolves the correct message set based on user's language preference.
/// </summary>
public static class MessageResolver
{
    /// <summary>
    /// Gets a message by key based on user's language.
    /// </summary>
    public static string Get(BotUser user, string key)
    {
        return user.Language switch
        {
            "en" => GetEn(key),
            "ru" => GetRu(key),
            _ => GetUz(key) // default: Uzbek
        };
    }

    private static string GetUz(string key) => key switch
    {
        "Welcome" => UzMessages.Welcome,
        "AlreadyRegistered" => UzMessages.AlreadyRegistered,
        "SelectLanguage" => UzMessages.SelectLanguage,
        "LangUzbek" => UzMessages.LangUzbek,
        "LangEnglish" => UzMessages.LangEnglish,
        "LangRussian" => UzMessages.LangRussian,
        "LanguageChanged" => UzMessages.LanguageChanged,
        "HelpText" => UzMessages.HelpText,
        "WeatherResult" => UzMessages.WeatherResult,
        "ForecastHeader" => UzMessages.ForecastHeader,
        "ForecastDay" => UzMessages.ForecastDay,
        "CityNotFound" => UzMessages.CityNotFound,
        "WeatherError" => UzMessages.WeatherError,
        "EnterCityName" => UzMessages.EnterCityName,
        "LocationSelectRegion" => UzMessages.LocationSelectRegion,
        "LocationSelectDistrict" => UzMessages.LocationSelectDistrict,
        "LocationBackToRegions" => UzMessages.LocationBackToRegions,
        "LocationEnterRegion" => UzMessages.LocationEnterRegion,
        "LocationEnterCity" => UzMessages.LocationEnterCity,
        "LocationRegionNotFound" => UzMessages.LocationRegionNotFound,
        "ReminderSuccess" => UzMessages.ReminderSuccess,
        "AlreadyReminded" => UzMessages.AlreadyReminded,
        "CancelReminderSuccess" => UzMessages.CancelReminderSuccess,
        "NotReminded" => UzMessages.NotReminded,
        "ReminderEnterCity" => UzMessages.ReminderEnterCity,
        "ReminderSelectHour" => UzMessages.ReminderSelectHour,
        "ReminderConfirm" => UzMessages.ReminderConfirm,
        "DailyReminderMessage" => UzMessages.DailyReminderMessage,
        "HistoryHeader" => UzMessages.HistoryHeader,
        "HistoryItem" => UzMessages.HistoryItem,
        "HistoryEmpty" => UzMessages.HistoryEmpty,
        "UserStats" => UzMessages.UserStats,
        "SubscribedYes" => UzMessages.SubscribedYes,
        "SubscribedNo" => UzMessages.SubscribedNo,
        "NoCity" => UzMessages.NoCity,
        "SettingsTitle" => UzMessages.SettingsTitle,
        "CurrentLangUz" => UzMessages.CurrentLangUz,
        "CurrentLangEn" => UzMessages.CurrentLangEn,
        "CurrentLangRu" => UzMessages.CurrentLangRu,
        "GeneralError" => UzMessages.GeneralError,
        "NoPermission" => UzMessages.NoPermission,
        "UnknownCommand" => UzMessages.UnknownCommand,
        "BotBanned" => UzMessages.BotBanned,
        "AdminWelcome" => UzMessages.AdminWelcome,
        "AdminStats" => UzMessages.AdminStats,
        "AdminUserList" => UzMessages.AdminUserList,
        "AdminUserItem" => UzMessages.AdminUserItem,
        "BroadcastPrompt" => UzMessages.BroadcastPrompt,
        "BroadcastDone" => UzMessages.BroadcastDone,
        "MakeAdminSuccess" => UzMessages.MakeAdminSuccess,
        "MakeAdminNotFound" => UzMessages.MakeAdminNotFound,
        "BanSuccess" => UzMessages.BanSuccess,
        "BanNotFound" => UzMessages.BanNotFound,
        "EnterUserIdForAdmin" => UzMessages.EnterUserIdForAdmin,
        "EnterUserIdForBan" => UzMessages.EnterUserIdForBan,
        "BtnWeather" => UzMessages.BtnWeather,
        "BtnForecast" => UzMessages.BtnForecast,
        "BtnReminder" => UzMessages.BtnReminder,
        "BtnCancelReminder" => UzMessages.BtnCancelReminder,
        "BtnHistory" => UzMessages.BtnHistory,
        "BtnStats" => UzMessages.BtnStats,
        "BtnRefresh" => UzMessages.BtnRefresh,
        "BtnReminderCity" => UzMessages.BtnReminderCity,
        "BtnMainMenu" => UzMessages.BtnMainMenu,
        "BtnConfirmYes" => UzMessages.BtnConfirmYes,
        "BtnConfirmNo" => UzMessages.BtnConfirmNo,
        "BtnAdminUsers" => UzMessages.BtnAdminUsers,
        "BtnAdminStats" => UzMessages.BtnAdminStats,
        "BtnAdminBroadcast" => UzMessages.BtnAdminBroadcast,
        "BtnAdminBan" => UzMessages.BtnAdminBan,
        "BtnAdminMakeAdmin" => UzMessages.BtnAdminMakeAdmin,
        "BtnSettings" => UzMessages.BtnSettings,
        "BtnChooseLocation" => UzMessages.BtnChooseLocation,
        "BtnNextPage" => UzMessages.BtnNextPage,
        "BtnPrevPage" => UzMessages.BtnPrevPage,
        "BtnBack" => UzMessages.BtnBack,
        "BtnChangeLanguage" => UzMessages.BtnChangeLanguage,
        _ => key
    };

    private static string GetEn(string key) => key switch
    {
        "Welcome" => EnMessages.Welcome,
        "AlreadyRegistered" => EnMessages.AlreadyRegistered,
        "SelectLanguage" => EnMessages.SelectLanguage,
        "LangUzbek" => EnMessages.LangUzbek,
        "LangEnglish" => EnMessages.LangEnglish,
        "LangRussian" => EnMessages.LangRussian,
        "LanguageChanged" => EnMessages.LanguageChanged,
        "HelpText" => EnMessages.HelpText,
        "WeatherResult" => EnMessages.WeatherResult,
        "ForecastHeader" => EnMessages.ForecastHeader,
        "ForecastDay" => EnMessages.ForecastDay,
        "CityNotFound" => EnMessages.CityNotFound,
        "WeatherError" => EnMessages.WeatherError,
        "EnterCityName" => EnMessages.EnterCityName,
        "LocationSelectRegion" => EnMessages.LocationSelectRegion,
        "LocationSelectDistrict" => EnMessages.LocationSelectDistrict,
        "LocationBackToRegions" => EnMessages.LocationBackToRegions,
        "LocationEnterRegion" => EnMessages.LocationEnterRegion,
        "LocationEnterCity" => EnMessages.LocationEnterCity,
        "LocationRegionNotFound" => EnMessages.LocationRegionNotFound,
        "ReminderSuccess" => EnMessages.ReminderSuccess,
        "AlreadyReminded" => EnMessages.AlreadyReminded,
        "CancelReminderSuccess" => EnMessages.CancelReminderSuccess,
        "NotReminded" => EnMessages.NotReminded,
        "ReminderEnterCity" => EnMessages.ReminderEnterCity,
        "ReminderSelectHour" => EnMessages.ReminderSelectHour,
        "ReminderConfirm" => EnMessages.ReminderConfirm,
        "DailyReminderMessage" => EnMessages.DailyReminderMessage,
        "HistoryHeader" => EnMessages.HistoryHeader,
        "HistoryItem" => EnMessages.HistoryItem,
        "HistoryEmpty" => EnMessages.HistoryEmpty,
        "UserStats" => EnMessages.UserStats,
        "SubscribedYes" => EnMessages.SubscribedYes,
        "SubscribedNo" => EnMessages.SubscribedNo,
        "NoCity" => EnMessages.NoCity,
        "SettingsTitle" => EnMessages.SettingsTitle,
        "CurrentLangUz" => EnMessages.CurrentLangUz,
        "CurrentLangEn" => EnMessages.CurrentLangEn,
        "CurrentLangRu" => EnMessages.CurrentLangRu,
        "GeneralError" => EnMessages.GeneralError,
        "NoPermission" => EnMessages.NoPermission,
        "UnknownCommand" => EnMessages.UnknownCommand,
        "BotBanned" => EnMessages.BotBanned,
        "AdminWelcome" => EnMessages.AdminWelcome,
        "AdminStats" => EnMessages.AdminStats,
        "AdminUserList" => EnMessages.AdminUserList,
        "AdminUserItem" => EnMessages.AdminUserItem,
        "BroadcastPrompt" => EnMessages.BroadcastPrompt,
        "BroadcastDone" => EnMessages.BroadcastDone,
        "MakeAdminSuccess" => EnMessages.MakeAdminSuccess,
        "MakeAdminNotFound" => EnMessages.MakeAdminNotFound,
        "BanSuccess" => EnMessages.BanSuccess,
        "BanNotFound" => EnMessages.BanNotFound,
        "EnterUserIdForAdmin" => EnMessages.EnterUserIdForAdmin,
        "EnterUserIdForBan" => EnMessages.EnterUserIdForBan,
        "BtnWeather" => EnMessages.BtnWeather,
        "BtnForecast" => EnMessages.BtnForecast,
        "BtnReminder" => EnMessages.BtnReminder,
        "BtnCancelReminder" => EnMessages.BtnCancelReminder,
        "BtnHistory" => EnMessages.BtnHistory,
        "BtnStats" => EnMessages.BtnStats,
        "BtnRefresh" => EnMessages.BtnRefresh,
        "BtnReminderCity" => EnMessages.BtnReminderCity,
        "BtnMainMenu" => EnMessages.BtnMainMenu,
        "BtnConfirmYes" => EnMessages.BtnConfirmYes,
        "BtnConfirmNo" => EnMessages.BtnConfirmNo,
        "BtnAdminUsers" => EnMessages.BtnAdminUsers,
        "BtnAdminStats" => EnMessages.BtnAdminStats,
        "BtnAdminBroadcast" => EnMessages.BtnAdminBroadcast,
        "BtnAdminBan" => EnMessages.BtnAdminBan,
        "BtnAdminMakeAdmin" => EnMessages.BtnAdminMakeAdmin,
        "BtnSettings" => EnMessages.BtnSettings,
        "BtnChooseLocation" => EnMessages.BtnChooseLocation,
        "BtnNextPage" => EnMessages.BtnNextPage,
        "BtnPrevPage" => EnMessages.BtnPrevPage,
        "BtnBack" => EnMessages.BtnBack,
        "BtnChangeLanguage" => EnMessages.BtnChangeLanguage,
        _ => key
    };

    private static string GetRu(string key) => key switch
    {
        "Welcome" => RuMessages.Welcome,
        "AlreadyRegistered" => RuMessages.AlreadyRegistered,
        "SelectLanguage" => RuMessages.SelectLanguage,
        "LangUzbek" => RuMessages.LangUzbek,
        "LangEnglish" => RuMessages.LangEnglish,
        "LangRussian" => RuMessages.LangRussian,
        "LanguageChanged" => RuMessages.LanguageChanged,
        "HelpText" => RuMessages.HelpText,
        "WeatherResult" => RuMessages.WeatherResult,
        "ForecastHeader" => RuMessages.ForecastHeader,
        "ForecastDay" => RuMessages.ForecastDay,
        "CityNotFound" => RuMessages.CityNotFound,
        "WeatherError" => RuMessages.WeatherError,
        "EnterCityName" => RuMessages.EnterCityName,
        "LocationSelectRegion" => RuMessages.LocationSelectRegion,
        "LocationSelectDistrict" => RuMessages.LocationSelectDistrict,
        "LocationBackToRegions" => RuMessages.LocationBackToRegions,
        "LocationEnterRegion" => RuMessages.LocationEnterRegion,
        "LocationEnterCity" => RuMessages.LocationEnterCity,
        "LocationRegionNotFound" => RuMessages.LocationRegionNotFound,
        "ReminderSuccess" => RuMessages.ReminderSuccess,
        "AlreadyReminded" => RuMessages.AlreadyReminded,
        "CancelReminderSuccess" => RuMessages.CancelReminderSuccess,
        "NotReminded" => RuMessages.NotReminded,
        "ReminderEnterCity" => RuMessages.ReminderEnterCity,
        "ReminderSelectHour" => RuMessages.ReminderSelectHour,
        "ReminderConfirm" => RuMessages.ReminderConfirm,
        "DailyReminderMessage" => RuMessages.DailyReminderMessage,
        "HistoryHeader" => RuMessages.HistoryHeader,
        "HistoryItem" => RuMessages.HistoryItem,
        "HistoryEmpty" => RuMessages.HistoryEmpty,
        "UserStats" => RuMessages.UserStats,
        "SubscribedYes" => RuMessages.SubscribedYes,
        "SubscribedNo" => RuMessages.SubscribedNo,
        "NoCity" => RuMessages.NoCity,
        "SettingsTitle" => RuMessages.SettingsTitle,
        "CurrentLangUz" => RuMessages.CurrentLangUz,
        "CurrentLangEn" => RuMessages.CurrentLangEn,
        "CurrentLangRu" => RuMessages.CurrentLangRu,
        "GeneralError" => RuMessages.GeneralError,
        "NoPermission" => RuMessages.NoPermission,
        "UnknownCommand" => RuMessages.UnknownCommand,
        "BotBanned" => RuMessages.BotBanned,
        "AdminWelcome" => RuMessages.AdminWelcome,
        "AdminStats" => RuMessages.AdminStats,
        "AdminUserList" => RuMessages.AdminUserList,
        "AdminUserItem" => RuMessages.AdminUserItem,
        "BroadcastPrompt" => RuMessages.BroadcastPrompt,
        "BroadcastDone" => RuMessages.BroadcastDone,
        "MakeAdminSuccess" => RuMessages.MakeAdminSuccess,
        "MakeAdminNotFound" => RuMessages.MakeAdminNotFound,
        "BanSuccess" => RuMessages.BanSuccess,
        "BanNotFound" => RuMessages.BanNotFound,
        "EnterUserIdForAdmin" => RuMessages.EnterUserIdForAdmin,
        "EnterUserIdForBan" => RuMessages.EnterUserIdForBan,
        "BtnWeather" => RuMessages.BtnWeather,
        "BtnForecast" => RuMessages.BtnForecast,
        "BtnReminder" => RuMessages.BtnReminder,
        "BtnCancelReminder" => RuMessages.BtnCancelReminder,
        "BtnHistory" => RuMessages.BtnHistory,
        "BtnStats" => RuMessages.BtnStats,
        "BtnRefresh" => RuMessages.BtnRefresh,
        "BtnReminderCity" => RuMessages.BtnReminderCity,
        "BtnMainMenu" => RuMessages.BtnMainMenu,
        "BtnConfirmYes" => RuMessages.BtnConfirmYes,
        "BtnConfirmNo" => RuMessages.BtnConfirmNo,
        "BtnAdminUsers" => RuMessages.BtnAdminUsers,
        "BtnAdminStats" => RuMessages.BtnAdminStats,
        "BtnAdminBroadcast" => RuMessages.BtnAdminBroadcast,
        "BtnAdminBan" => RuMessages.BtnAdminBan,
        "BtnAdminMakeAdmin" => RuMessages.BtnAdminMakeAdmin,
        "BtnSettings" => RuMessages.BtnSettings,
        "BtnChooseLocation" => RuMessages.BtnChooseLocation,
        "BtnNextPage" => RuMessages.BtnNextPage,
        "BtnPrevPage" => RuMessages.BtnPrevPage,
        "BtnBack" => RuMessages.BtnBack,
        "BtnChangeLanguage" => RuMessages.BtnChangeLanguage,
        _ => key
    };
}
